### ISSUE TITLE
Issue and Comment structs aren't consistent

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#1448] opened 2022-01-07 22:37 UTC
The issue date is a pointer
https://github.com/ossf/scorecard/blob/192ae4d18fbaaeb7d2510b1116c26c817825e210/clients/issue.go#L22

whereas the commit date is not a pointer
https://github.com/ossf/scorecard/blob/192ae4d18fbaaeb7d2510b1116c26c817825e210/clients/commit.go#L21

This needs to be consistent.

**Comment by naveensrinivasan** [comment] 2022-01-07 22:37
@azeemshaikh38 FYI...

**Comment by azeemshaikh38** [comment] 2022-01-11 17:34
Thanks for bringing this up. I think #1242 should have handled this, but I mistakenly closed the issue before completing it. I'm marking this as duplicate of #1242

**Closed** 2022-01-11 17:35 UTC
