### ISSUE TITLE
Cannot scan self-hosted (private) GitLab repositories

### ISSUE THREAD

**Issue by mwager** [ossf/scorecard#3696] opened 2023-11-28 07:28 UTC
**Describe the bug**
Cannot scan self-hosted (private) GitLab repositories

**Reproduction steps**
1. See screenshot

Shouldnt this be possible acc. to your blogpost?

_You can run Scorecard today on a GitLab.com (or self-hosted GitLab) repository by running Scorecard as you normally would_

https://openssf.org/blog/2023/08/28/openssf-scorecard-launches-v4-12-with-support-for-gitlab/

Thank you!

![grafik](https://github.com/ossf/scorecard/assets/999748/7991aa03-df83-4b3b-a91f-6932e1ffa73d)

**Comment by spencerschrock** [comment] 2023-11-28 17:35
Our code tries to create a GitLab client first, and then falls back to GitHub.
https://github.com/ossf/scorecard/blob/04ea8bee4898d042ca8d7cc947a42d401d435340/checker/client.go#L58-L75

Since it's falling back to GitHub, there was some sort of error making the GitLab one, which we unfortunately aren't surfacing.

My guess is this has to do with auth tokens since we don't pass one in here.
https://github.com/ossf/scorecard/blob/04ea8bee4898d042ca8d7cc947a42d401d435340/clients/gitlabrepo/repo.go#L98-L114

**Comment by spencerschrock** [comment] 2023-11-28 17:38
If you're able to try building locally, can you try this patch?
```diff
diff --git a/checker/client.go b/checker/client.go
index 1b5d28a3..d9570773 100644
--- a/checker/client.go
+++ b/checker/client.go
@@ -61,6 +61,7 @@ func GetClients(ctx context.Context, repoURI, localURI string, logger *log.Logge
 	}
 
 	if makeRepoError != nil || repo == nil {
+		fmt.Println(makeRepoError)
 		repo, makeRepoError = ghrepo.MakeGithubRepo(repoURI)
 		if makeRepoError != nil {
 			return repo,
diff --git a/clients/gitlabrepo/repo.go b/clients/gitlabrepo/repo.go
index 65a44783..1a371ed6 100644
--- a/clients/gitlabrepo/repo.go
+++ b/clients/gitlabrepo/repo.go
@@ -97,7 +97,7 @@ func (r *repoURL) String() string {
 
 // IsValid implements Repo.IsValid.
 func (r *repoURL) IsValid() error {
-	if strings.Contains(r.host, "gitlab.") {
+	if strings.Contains(r.host, "gitlab") {
 		return nil
 	}
 
```

**Comment by mwager** [comment] 2023-11-30 08:42
Hey, thanks for the fast answer! I tried to install but I am not very familiar with go, getting lot of errors...

But your patch makes sense to me, the url looks like this:

`https://foo.bar.com/gitlab/org/repo`

running it like:

`scorecard --repo https://foo.bar.com/gitlab/org/repo --format=json`

**Comment by spencerschrock** [comment] 2023-12-06 21:43
> If you know how to fix this asm error I could try again

Hmm, I can't say I've seen the error before. A quick search says it's something preventing you from running the asm binary, either antivirus, or maybe all of the Go binaries aren't in your path, or there's conflicting versions of Go installed?

Maybe check you're seeing the expected things when running:
```console
which go
```

Depending on the results, you can try setting your GOROOT and GOPATH.
```console
export GOROOT=`which go`
export PATH=$GOROOT/bin:$PATH
```

Another alternative is compiling on your laptop and transfering the binary to the centos machine (if possible)

**Comment by mwager** [comment] 2023-12-11 10:21
I fixed it via installing a fresh go bin and running scorecard directly.

Seems like there is an issue reaching the gitlab instance, but strange error regarding "invalid character <" is thrown.

![grafik](https://github.com/ossf/scorecard/assets/999748/740536fb-9f23-4aa4-943d-c20a4164c7b9)

However trying wget the connection works:

![grafik](https://github.com/ossf/scorecard/assets/999748/3cdcba97-96ea-4971-b2cc-b1329087fc70)

**Comment by spencerschrock** [comment] 2023-12-11 17:51
> Seems like there is an issue reaching the gitlab instance, but strange error regarding "invalid character <" is thrown.

Thanks, I think this error helps confirm the GitLab server is responding with HTML (possibly a 404 since Scorecard isn't using the user-provided token for this call). The library we use is trying to parse the HTML as a JSON response, leading to the invalid character message.

> Update: I exported a valid gitlab token

Just to confirm, exporting the token didn't fix it? If you want to try something while we discuss fixing it, i would try replacing `""` in this line with `os.Getenv("GITLAB_AUTH_TOKEN")`, in order to send your PAT to your instance:
https://github.com/ossf/scorecard/blob/5dc03b72e109d67afe4c91a0fbe52a3c1678a97f/clients/gitlabrepo/repo.go#L108

Resulting in:
```go
client, err := gitlab.NewClient(os.Getenv("GITLAB_AUTH_TOKEN"), gitlab.WithBaseURL(fmt.Sprintf("%s://%s", r.scheme, r.host)))
```

@raghavkaul Thoughts on solving this? My suggested patch in the other comment (https://github.com/ossf/scorecard/issues/3696#issuecomment-1830365830)  wouldn't be enough since the "gitlab" part of the URL is in the path not the host. We could try a `GL_HOST` env var similar to what we do in the github version of `IsValid()` (`GH_HOST`)?  

 Or there's the fix to the "liveness" check I mention in this comment, but are there situations where we should be worried about doing this, in terms of sending a PAT to an instance it may not correspond to? Although I'm not sure any solution would prevent that, as the actual analysis part of the code will send the token.

**Comment by mwager** [comment] 2023-12-12 07:07
Oh yes I though this error reminds me on something :)

I tried your patch passing the token as first paramneter to `NewClient(`, it does not solve the issue:

![grafik](https://github.com/ossf/scorecard/assets/999748/0bf6cfe9-9e71-4e7b-8300-04b569ef0777)

**Comment by spencerschrock** [comment] 2023-12-19 15:36
Hmm, i wonder if the API link is different from what we're expecting:

So with gitlab.com, the API link is: `https://gitlab.com/api/v4/` and then the rest of the path, for example: https://gitlab.com/api/v4/projects
But based on your screenshots, your instance is at `https://foo.com/gitlab/`, so I'm guessing the api link is different.
 Maybe something like: `https://foo.com/gitlab/api/v4/`?
 
 Does https://foo.com/gitlab/api/v4/projects resolve for you (after replacing foo.com with your domain?)
 
 If so, the problematic code changes to here, where we just add `api/v4/` to the end of whatever the host is:
 https://github.com/ossf/scorecard/blob/2ef20f17fb2e64147c83440cd2c769653454015a/checker/client.go#L59-L62

**Comment by mwager** [comment] 2023-12-20 07:08
Hi,

yes https://foo.com/gitlab/api/v4/projects resolves for me!

I added this code:

![grafik](https://github.com/ossf/scorecard/assets/999748/7491b4b9-8fbf-4099-8f96-25b49c7271ca)


`repoURI` is smt like `https://foo.com/gitlab/someorg/someproject`

Still same error. Token exported.

Maybe you are also missing `projects` like documented here: https://docs.gitlab.com/ee/api/api_resources.html#project-resources

See this curl command works for me:

![grafik](https://github.com/ossf/scorecard/assets/999748/88a89dc1-fb86-4a03-b9d6-50f7e979e93e)

So the URL has to be `https://foo.com/gitlab/api/v4/projects/namespace%2Fname`

See this: https://stackoverflow.com/questions/54717065/get-the-id-of-gitlab-project-via-gitlab-api-or-gitlab-cli

id: The ID or [URL-encoded path of the project](https://docs.gitlab.com/ee/api/README.html#namespaced-path-encoding)


Let me know if I can help testing or anything.

**Comment by spencerschrock** [comment] 2023-12-28 21:29
> yes https://foo.com/gitlab/api/v4/projects resolves for me!
> See this curl command works for me:

I think we've found the issue. Your code patch was close, but `repo.Host()` only takes the (sub)domain portion of the URL (`foo.com` in this case), which doesn't include the `gitlab` part of your URL. So you still ended up with `https://foo.com/api/v4/` instead of `https://foo.com/gitlab/api/v4/`

I've pushed a quick workaround to a [branch in my fork](https://github.com/spencerschrock/scorecard/tree/fix/gitlab-host-path), where the only patch compared to `main` is https://github.com/ossf/scorecard/commit/22bc2733c8897431fce577d84db12a720725034e.

Can you give that a shot, but make sure you set the `GL_HOST` environment variable to `foo.com/gitlab/`
```console
GL_HOST=foo.com/gitlab/ go run main.go --repo https://foo.com/gitlab/ssdlc/scorecard-scanner --format json
```

If that works, I'll clean it up before sending a PR.

**Comment by spencerschrock** [comment] 2023-12-28 21:38
And if that complains about "couldn't reach gitlab instance", it probably needs to be combined with token patch above.

```go
host := r.host
if h := os.Getenv("GL_HOST"); h != "" {
	// avoid duplication of the scheme when constructing baseURL below
	host = strings.TrimPrefix(h, r.scheme+"://")
}
baseURL := fmt.Sprintf("%s://%s", r.scheme, host)
client, err := gitlab.NewClient(os.Getenv("GITLAB_AUTH_TOKEN"), gitlab.WithBaseURL(baseURL))
```

**Comment by mwager** [comment] 2023-12-29 09:46
Tried your patch, incl the token patch above. Looks better now, now it is using the host including `/gitlab` but then also tries to fetch `gitlab/ssdlc/scorecard-scanner` instead of just `ssdlc/scorecard-scanner`

Did I do smt wrong?

![grafik](https://github.com/ossf/scorecard/assets/999748/3cfaaf9a-e080-4c8f-81bb-d434e4fb8b92)

**Comment by spencerschrock** [comment] 2024-01-09 19:07
> Tried your patch, incl the token patch above. Looks better now, now it is using the host including `/gitlab` but then also tries to fetch `gitlab/ssdlc/scorecard-scanner` instead of just `ssdlc/scorecard-scanner`
> 
> Did I do smt wrong?


Nope, my patch was just an incomplete solution, but we've confirmed the issue in question. Will need to think about how to handle this. Probably would involve changes to the how we parse the repo:
https://github.com/ossf/scorecard/blob/45425b68a2c89986f3cb8fd8ad63c7ba81d0bb00/clients/gitlabrepo/repo.go#L53

I might have some time later this week to poke around again.

**Comment by spencerschrock** [comment] 2024-01-19 23:22
Can you give it another shot with the changes I pushed to the branch today? (sorry for all the "try this", don't have a setup to test on)

I made sure to add the token changes too. So hopefully the branch HEAD (d3d5ba64a6f52593b222c67fc5076a47c666c54f) works.

If it doesn't, give HEAD~1 (22d788c2cea820427c4a39ac579e33a2bb1ff7de) a try too.

**Comment by mwager** [comment] 2024-01-23 06:53
No problem, I would be very glad to help :)

I pulled your repo, and did `git checkout fix/gitlab-host-path`

Looks good!

![grafik](https://github.com/ossf/scorecard/assets/999748/46682733-a0c9-46a6-bf5a-323665111474)

Throws an error after the results:

![grafik](https://github.com/ossf/scorecard/assets/999748/732ad67c-4e7d-40a5-b03f-dbd8d91906fe)

**Comment by spencerschrock** [comment] 2024-01-23 18:51
> Throws an error after the results

In this particular case, I think the fix is in `main` already (I haven't pulled in updates to this branch since I forked it ~1 month ago). I'll work later this week on getting this up as a PR

**Comment by mwager** [comment] 2024-01-24 06:04
Nice, let me know if I can help review & test the PR...

**Closed** 2024-01-31 18:04 UTC
Labels: bug, gitlab

**Comment by mwager** [comment] 2024-02-01 06:30
Thank you so much! 🫶🏻
