### ISSUE TITLE
make install fails due to checksum mismatch

### ISSUE THREAD

**Issue by ipuustin** [ossf/scorecard#2258] opened 2022-09-13 10:09 UTC
**Describe the bug**

`make install` fails due to a checksum mismatch.

**Reproduction steps**
1.  Checkout latest main branch (bde0ae166a7f56f957d983a60e7316054255624f)
2.  Say `make install`

Outcome is this:

```
...
go: downloading cloud.google.com/go/kms v1.4.0
verifying github.com/goreleaser/chglog@v0.2.0: checksum mismatch
        downloaded: h1:/vAHEwZvXEe41X16Abobo4yLxxuYo9ZiSw9FgrxQ0cU=
        go.sum:     h1:thKIYjrg5YrsuH1BzDZHQlvFwZxFNZC8YpK+sGJQPMk=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
go install github.com/naveensrinivasan/stunning-tribble
go: downloading github.com/naveensrinivasan/stunning-tribble v0.4.2
go install github.com/onsi/ginkgo/v2/ginkgo
go: downloading github.com/onsi/ginkgo/v2 v2.1.6
go: downloading github.com/google/pprof v0.0.0-20220729232143-a41b82acbcb1
go install google.golang.org/protobuf/cmd/protoc-gen-go
make: *** [Makefile:39: install] Error 123
```

**Expected behavior**

Expected `make install` to succeed without error.

**Additional context**
Fedora 36, `go version go1.18.5 linux/amd64`.

**Comment by naveensrinivasan** [comment] 2022-09-13 10:36
Thanks.

But I am not able to reproduce the error.

``` bash
Identity added: /Users/naveen/.ssh/id_ed25519 (172697+naveensrinivasan@users.noreply.github.com)
➜  scorecard git:(main) go version
go version go1.18.4 darwin/arm64
➜  scorecard git:(main) make install
Installing tools from tools/tools.go
cd tools; cat tools.go | grep _ | awk -F'"' '{print $2}' | xargs -tI % go install %
go install github.com/golang/mock/mockgen
go install github.com/golangci/golangci-lint/cmd/golangci-lint
go install github.com/google/addlicense
go install github.com/google/ko
go install github.com/goreleaser/goreleaser
go install github.com/naveensrinivasan/stunning-tribble
go install github.com/onsi/ginkgo/v2/ginkgo
go install google.golang.org/protobuf/cmd/protoc-gen-go
➜  scorecard git:(main) git rev-parse HEAD
bde0ae166a7f56f957d983a60e7316054255624f

```

**Comment by naveensrinivasan** [comment] 2022-09-16 15:12
Closing it! Please reopen if you still see an issue. Thanks

**Closed by naveensrinivasan** 2022-09-16 15:12 UTC
Labels: bug
