### ISSUE TITLE
Improve Score Reporting: Token-Permissions on repo without GitHub workflows

### ISSUE THREAD

**Issue by azeemshaikh38** [ossf/scorecard#2158] opened 2022-08-17 01:21 UTC
`Token-Permissions` check returns `10` on repositories which do not have any GH workflows. We should consider improving our reporting here. 

```
./scorecard --repo=azeemshaikh38/empty-repo-test --format=json --checks=Token-Permissions --show-details | jq .
2022/08/17 01:20:11 unable to get tarball tarball not found: https://api.github.com/repos/azeemshaikh38/empty-repo-test/tarball/. Skipping...
{
  "date": "2022-08-17",
  "repo": {
    "name": "github.com/azeemshaikh38/empty-repo-test",
    "commit": "no commits found"
  },
  "scorecard": {
    "version": "v4.5.0-25-g887facf",
    "commit": "887facf3cad2bd401ff5f6a51725225f8ec28c17"
  },
  "score": 10,
  "checks": [
    {
      "details": null,
      "score": 10,
      "reason": "tokens are read-only in GitHub workflows",
      "name": "Token-Permissions",
      "documentation": {
        "url": "https://github.com/ossf/scorecard/blob/887facf3cad2bd401ff5f6a51725225f8ec28c17/docs/checks.md#token-permissions",
        "short": "Determines if the project's workflows follow the principle of least privilege."
      }
    }
  ],
  "metadata": null
}
```

**Comment by azeemshaikh38** [comment] 2023-04-18 15:28
@raghavkaul fyi.

**Comment by spencerschrock** [comment] 2023-08-01 21:10
I'd consider this still relevant yes, although I think the discussion is taking place in #3205

**Comment by leec94** [comment] 2023-08-03 14:51
Would this issue be a duplicate of that issue then? I'm unclear of the result of the discussion is there too, and if work needs to be done.

**Comment by spencerschrock** [comment] 2023-08-23 17:47
> Would this issue be a duplicate of that issue then? I'm unclear of the result of the discussion is there too, and if work needs to be done.

I interpreted this issue as saying:
> it's confusing to have `tokens are read-only in GitHub workflows` as a reason when there's no tokens

Which the reason strings have been changed already to:
* `no github tokens found` for `Token-Permissions`
* `no workflows found` for `Dangerous-Workflow`

**Comment by leec94** [comment] 2023-08-23 21:11
Sure, I also see the new `reason` being shown when doing a test run of the latest code, with a result of -1. This looks fine to me to close out if it's ok with others.  
```
carolinelee@Carolines-MBP scorecard % go run main.go --repo=github.com/ossf/artwork --format=json --checks=Token-Permissions --show-details | jq .
{
  "date": "2023-08-23T17:08:16-04:00",
  "repo": {
    "name": "github.com/ossf/artwork",
    "commit": "70c1012bf5f2a97cdf5335f041f087a74150b7e5"
  },
  "scorecard": {
    "version": "",
    "commit": "unknown"
  },
  "score": -1,
  "checks": [
    {
      "details": null,
      "score": -1,
      "reason": "no github tokens found",
      "name": "Token-Permissions",
      "documentation": {
        "url": "https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions",
        "short": "Determines if the project's workflows follow the principle of least privilege."
      }
    }
  ],
  "metadata": null
}
```

Question, might be a tangent though. When trying it on the same repo as the description, I get no results. Is this issue happening for others too? 

```
carolinelee@Carolines-MBP scorecard % go run main.go --repo=github.com/azeemshaikh38/empty-repo-test --format=json --checks=Token-Permissions --show-details | jq .
{
  "date": "0001-01-01T00:00:00Z",
  "repo": {
    "name": "",
    "commit": ""
  },
  "scorecard": {
    "version": "",
    "commit": ""
  },
  "score": -1,
  "checks": null,
  "metadata": null
}
```

**Comment by spencerschrock** [comment] 2023-08-23 21:39
> Sure, I also see the new `reason` being shown when doing a test run of the latest code, with a result of -1. This looks fine to me to close out if it's ok with others.

Agreed. The score discussion is happening in #3205, so good with closing this out.

> Question, might be a tangent though. When trying it on the same repo as the description, I get no results. Is this issue happening for others too?

See #2157 for more details. There still may be some improvement possible there.

**Closed by spencerschrock** 2023-08-23 21:39 UTC
Labels: bug, good first issue, hacktoberfest, score reporting
