### ISSUE TITLE
Sign up for CII Best Practices 

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#174] opened 2021-02-14 03:00 UTC
Sign up for CII Best Practices.

https://bestpractices.coreinfrastructure.org/en

**Comment by naveensrinivasan** [comment] 2021-02-14 03:01
Needs to org level GitHub permission for CII to view the score card repo.

**Comment by azeemshaikh38** [comment] 2022-01-28 02:12
Might be a good issue for our next milestone. Re-opening.

**Comment by azeemshaikh38** [comment] 2022-02-13 05:28
Duplicate of #1032. Closing this and tracking it there.

**Closed by azeemshaikh38** 2022-02-13 05:28 UTC
Labels: help wanted
