### ISSUE TITLE
Scorecard scan of a particular branch of the Target Repo

### ISSUE THREAD

**Issue by sprathod369** [ossf/scorecard#2642] opened 2023-02-06 11:00 UTC
I've just started exploring scorecard so have a basic question. I'm running this tool using CLI in docker mode and the usage documentation mentions to provide the Git URL of the target repo. However, I do not see any parameter on the branch that we want to target for running the scorecard analysis.
Does the scorecard scan work on the default branch of the repo only or is it that the branch of the Git repo does not really matter for the scorecard analysis?

Thanks!!

**Comment by spencerschrock** [comment] 2023-02-23 19:49
Right now Scorecard can only look at the default branch.
Some of the checks rely on repository settings which don't change from branch to branch.

**Comment by azeemshaikh38** [comment] 2023-02-23 23:15
Marking as Duplicate of #1709. We need to support git natively for this to work.

**Closed** 2023-05-03 01:52 UTC
Labels: no-issue-activity
