### ISSUE TITLE
Detect GitHub secret scanning

### ISSUE THREAD

**Issue by coheigea** [ossf/scorecard#3399] opened 2023-08-18 08:20 UTC
It would be nice if we could detect if GitHub secret scanning was enabled, and if push protection was enabled for secrets, and update the overall score accordingly.

<img width="848" alt="secret-scanning" src="https://github.com/ossf/scorecard/assets/472162/da5c643d-5af7-445f-8912-c9785f81c502">

**Comment by spencerschrock** [comment] 2023-08-18 16:56
It's accessible via an API, but requires administration read permissions (similar to the webhook check).
https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#get-a-repository
```
"security_and_analysis": {
      "advanced_security": {
        "status": "enabled"
      },
      "secret_scanning": {
        "status": "enabled"
      },
      "secret_scanning_push_protection": {
        "status": "disabled"
      }
}
```

I'm guessing we need some changes on our side to handle these admin level self-auditing checks. As I don't like the idea of having a bunch of inconclusive `-1` or `?` results in every scorecard result. Either self detecting the token's access level, with an error specific to "not an admin", or a flag (`--admin` maybe?), which lets us include/exclude these checks.

**Comment by spencerschrock** [comment] 2023-08-18 18:28
Let's keep discussion in one place. Closing as this is a duplicate of #30

**Closed by spencerschrock** 2023-08-18 18:28 UTC
Labels: enhancement
