### ISSUE TITLE
BUG: Code-review check result is wrong

### ISSUE THREAD

**Issue by bhuvi11** [ossf/scorecard#895] opened 2021-08-24 12:50 UTC
Hello Team,

I see that the code review check is not providing the right result,

> {
      "Details": [
        "found pr with committer different than author: 1",
        "found pr with committer different than author: 2",
        "found pr with committer different than author: 9",
        "found pr with committer different than author: 33",
        "Gerrit code reviews found for 0 commits out of the last 30",
        "Prow code reviews found for 0 commits out of the last 4"
      ],
      "Score": 10,
      "Reason": "GitHub code reviews found for 4 commits out of the last 4 -- score normalized to 10",
      "Name": "Code-Review"
    },

Here the pr number 33 is having bhuvi11 as the author and committer, but it is mentioned as different.
Why is it so?

PR for reference

> https://github.com/bhuvi11/ecom-service/pull/33/commits

Thanks in advance

**Comment by azeemshaikh38** [comment] 2021-08-24 14:53
The GitHub API returns the committer of the PR as `null` which leads to Scorecard recognizing author and committer as different. Giving a score of `10` here seems like the wrong behavior. @laurentsimon this is an interesting corner case to look into.

**Comment by laurentsimon** [comment] 2021-08-24 15:54
@bhuvi11 thanks for the report!

Can you give me the steps to reproduce the problem (and how the PR was merged)? Example:
1. Create a branch on the same repo
2. XXX
3. etc

I need to figure out why the committer is `null` and whether we can tweak the message/score.

**Comment by bhuvi11** [comment] 2021-08-25 03:50
Hello @laurentsimon,
Sure

- I have created a branch called testing
- I made a change 
- I raised a PR and merged it with master

Pull request :  

> https://github.com/bhuvi11/ecom-service/pull/40

Branch successfully merged

**Comment by bhuvi11** [comment] 2021-09-02 06:45
Hello @laurentsimon,
Thanks a lot for the response.
What is that i need to do?

**Comment by laurentsimon** [comment] 2021-09-08 22:26
@azeemsgoogle recently updated this code with GraphQl. It may have fixed the problem. Can you run check if the changes have fixed the problem?

**Comment by bhuvi11** [comment] 2021-09-09 03:55
Hello @laurentsimon,

I just ran and got this as my result 
{
         "details":[
            "Info: Gerrit code reviews found for 0 commits out of the last 30",
            "Info: Prow code reviews found for 0 commits out of the last 5"
         ],
         "score":10,
         "reason":"GitHub code reviews found for 5 commits out of the last 5 -- score normalized to 10",
         "name":"Code-Review"
      }
I believe i got score 10 because code review were done for all the commits? So it is a good case right ?

**Comment by laurentsimon** [comment] 2021-09-09 20:09
I think that's incorrect, because you reviewed your own commits.  @azeemsgoogle is there a way to fix this with codeQL? (the value seems to be returned by the server https://github.com/ossf/scorecard/blob/main/clients/githubrepo/graphql.go#L151)

**Comment by bhuvi11** [comment] 2021-09-24 03:10
Hello @laurentsimon , So this issue is resolved?

**Comment by azeemshaikh38** [comment] 2021-09-24 03:35
I don't think so. @laurentsimon could you please look into this?

```
./scorecard --repo=bhuvi11/ecom-service --checks=Code-Review
Starting [Code-Review]
Finished [Code-Review]

RESULTS
-------
Aggregate score: 10.0 / 10

Check scores:
|---------|-------------|--------------------------------|------------------------------------------------------------------------------------------------------------|
|  SCORE  |    NAME     |             REASON             |                                         DOCUMENTATION/REMEDIATION                                          |
|---------|-------------|--------------------------------|------------------------------------------------------------------------------------------------------------|
| 10 / 10 | Code-Review | GitHub code reviews found for  | https://github.com/ossf/scorecard/blob/aa93ac232925102ff71023081932f8630778d2bf/docs/checks.md#code-review |
|         |             | 5 commits out of the last 5 -- |                                                                                                            |
|         |             | score normalized to 10         |                                                                                                            |
|---------|-------------|--------------------------------|------------------------------------------------------------------------------------------------------------|

```

**Closed** 2021-09-24 03:56 UTC
Labels: bug, help wanted, priority, v3
