### ISSUE TITLE
BUG: dependabot detected in a project without dependabot

### ISSUE THREAD

**Issue by pnacht** [ossf/scorecard#3124] opened 2023-06-05 14:44 UTC
**Describe the bug**
[google/brotli](https://github.com/google/brotli/tree/master/.github) doesn't have dependabot installed. However, Scorecard (4.10.5) gives the project a 10/10 for Dependency-Update-Tool, stating it does have dependabot.

**Reproduction steps**
`scorecard --repo google/brotli --show-details --checks Dependency-Update-Tool --format json`

```json
    [...]
    {
      "details": [
        "Info: Dependabot detected"
      ],
      "score": 10,
      "reason": "update tool detected",
      "name": "Dependency-Update-Tool",
      "documentation": {
        "url": "https://github.com/ossf/scorecard/blob/27cfe92ed356fdb5a398c919ad480817ea907808/docs/checks.md#dependency-update-tool",
        "short": "Determines if the project uses a dependency update tool."
      }
    },
```

**Expected behavior**
The project should get a 0/10 for Dependency-Update-Tool

**Additional context**
Interestingly enough, this project actually also suffers from https://github.com/ossf/scorecard/issues/2489 since they define a `.gitattributes` file that excludes the `.github` folder entirely, so Scorecard wouldn't find a `dependabot.yml` file even if there was one.

And oddly enough, the project did receive a single dependabot PR (https://github.com/google/brotli/pull/853) in 2020, even though the `.github` folder's history never had a `dependabot.yml` file...

**Comment by spencerschrock** [comment] 2023-06-06 16:45
Thanks for another data point. This is a duplicate of #2845, so going to close this one so we have a single report.

**Closed by spencerschrock** 2023-06-06 16:45 UTC
Labels: bug
